export const defaultCategories = [
    { name: 'Electronics' },
    { name: 'Groceries' },
    { name: 'Clothing' },
    { name: 'Household Items' },
    { name: 'Books' },
    { name: 'Toys' },
    { name: 'Furniture' },
    { name: 'Health & Beauty' },
    { name: 'Sports' },
    { name: 'Automotive' },
    { name: 'Tools' },
    { name: 'Jewelry' },
    { name: 'Music' },
    { name: 'Movies' },
    { name: 'Games' },
    { name: 'Pet Supplies' },
    { name: 'Office Supplies' },
    { name: 'Baby' },
    { name: 'Industrial' },
    { name: 'Software' },
    { name: 'Home Improvement' },
    { name: 'Arts & Crafts' },
    { name: 'Food & Drink' },
    { name: 'Electrical' },
    { name: 'Garden' },
    { name: 'Travel' },
    { name: 'Miscellaneous' },
  ];